version: "3"
services:
  node:
    build: .
    command: "npm run dev"
    working_dir: /home/node/app
    expose:
      - "3333"
    ports:
      - "3333:3333"
    volumes: 
      - .:/home/node/app
    
    