name: Pipeline Auth Rype CI
on:
  push:
    branchs:
      - [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repo
        uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.REMOTE_HOST }}
          USERNAME: ${{ secrets.REMOTE_USER }}
          KEY: ${{ secrets.SERVER_SSH_KEY }}
          PORT: 22
          source: "."
          target: "home/api.rypegg.com/auth"

      - name: Deploy Produção
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: | 
            cd /
            cd home/api.rypegg.com/auth
            ls
            
          
        
