name: Pipeline Auth Rype CI
on:
  push:
    branchs:
      - [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repo
        uses: actions/checkout@v3

      - name: Deploy para Producao
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: "-rlgoDzvc -i --delete"
            SOURCE: "/"
            PORT: 22
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: /home/api.rypegg.com/auth
            
          
        
