name: Pipeline Auth Rype CI
on:
  push:
    branchs:
      - [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repo
        uses: actions/checkout@v3

      - name: Deploy para Producao
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: "/"
          PORT: 22
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/auth.api.rypegg.com/public_html
      - name: Comandos em produção
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: | 
          cd /
          cd home/api.rypegg.com/auth
          echo hello world > hello.txt
