name: Pipeline Auth Rype CI
on:
  push:
    branchs:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repo
        uses: actions/checkout@v1
      - name: Deploy Produção
        uses: easingthemes/ssh-deploy@master
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "src/"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          REMOTE_PORT: ${{secrets.REMOTE_PORT}}
          TARGET: ${{secrets.TARGET}}
